name: QuestionGenerationServer
channels:
 - defaults
dependencies:
 - python=3.8
 - Flask
 - pytorch
 - numpy
 - transformers
 - pillow
 - requests
 - oauthlib
 - pyOpenSSL
 - Flask-Login
 - psycopg2
 - aioflask
  
